'use client';
import React,{useRef,useState} from 'react';
import { apiRequest } from '../../lib/api';
import { createFacebookRequestGuard,facebookSendNotice,type FacebookComment,type FacebookPage,type FacebookSendResult } from '../../lib/facebookEngagement';
import { useLanguage } from '../LanguageProvider';
export function FacebookCommentsView({items,missingPostId,canReply,error,busy,drafts,onDraft,onReply,onRefresh}:{items:FacebookComment[];missingPostId:boolean;canReply:boolean;error:string|null;busy:boolean;drafts:Record<string,string>;onDraft(id:string,text:string):void;onReply(id:string):void;onRefresh():void}){
  const {t}=useLanguage();return <section className="instagram-engagement-panel"><div className="button-row"><strong>{t('Facebook 帖子评论','Facebook post comments')}</strong><button type="button" className="button secondary" disabled={busy||missingPostId} onClick={onRefresh}>{t('读取评论','Read comments')}</button></div>
    {error?<p className="error" role="alert">{error}</p>:null}{missingPostId?<p className="muted">{t('真实帖子 ID 不可用，暂时无法读取评论。','The real post ID is unavailable; comments cannot be read yet.')}</p>:!items.length && !error?<p className="muted">{t('暂无评论（请先读取评论）','No comments loaded; read comments first.')}</p>:null}
    {items.map(comment=><article key={comment.id} className="instagram-comment"><strong>{comment.senderName??t('客户','Customer')}</strong><p>{comment.text||t('非文字评论','Non-text comment')}</p><small>{new Date(comment.timestamp).toLocaleString(undefined,{timeZone:'Asia/Shanghai'})}</small>
      {canReply?<div className="instagram-reply-form"><input aria-label={t('回复评论','Comment reply')} value={drafts[comment.id]??''} maxLength={2000} disabled={busy} onChange={e=>onDraft(comment.id,e.target.value)}/><button type="button" disabled={busy||!(drafts[comment.id]??'').trim()} onClick={()=>onReply(comment.id)}>{t('发送回复','Send reply')}</button></div>:null}</article>)}</section>;
}
export function FacebookPostComments({token,workspaceId,scheduleId,providerPostId,role}:{token:string;workspaceId:string;scheduleId:string;providerPostId?:string|null;role?:string}){
  const {locale}=useLanguage(),guard=useRef(createFacebookRequestGuard());guard.current.reset(`${token}:${workspaceId}:${scheduleId}`);
  const [expanded,setExpanded]=useState(false),[items,setItems]=useState<FacebookComment[]>([]),[cursor,setCursor]=useState<string|null>(null),[drafts,setDrafts]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState(''),[fetchedAt,setFetchedAt]=useState('');
  const base=`/workspaces/${encodeURIComponent(workspaceId)}/facebook/posts/${encodeURIComponent(scheduleId)}/comments`;
  async function read(after?:string){setBusy(true);try{const result=await guard.current.run('comments',()=>apiRequest<FacebookPage<FacebookComment>>(base+(after?`?after=${encodeURIComponent(after)}`:''),{token}));if(result.current){setItems(current=>after?[...current,...result.value.items]:result.value.items);setCursor(result.value.nextCursor);setFetchedAt(new Date().toLocaleString(undefined,{timeZone:'Asia/Shanghai'}));setError(null);}}catch(e){setError(e instanceof Error?e.message:'Facebook unavailable');}finally{setBusy(false);}}
  async function reply(id:string){setBusy(true);try{const result=await guard.current.send(()=>apiRequest<FacebookSendResult>(`${base}/${encodeURIComponent(id)}/replies`,{token,method:'POST',body:{text:drafts[id]}}));if(result.current){setNotice(facebookSendNotice(result.value,locale));if(result.value.status==='sent'){setDrafts(current=>({...current,[id]:''}));void read();}}}catch(e){setError(e instanceof Error?e.message:'Facebook unavailable');}finally{setBusy(false);}}
  return <div><button type="button" className="button secondary" onClick={()=>setExpanded(!expanded)}>{locale==='en'?'Facebook comments':'Facebook 评论'}</button>{expanded?<><FacebookCommentsView items={items} missingPostId={!providerPostId} canReply={['owner','admin','editor'].includes(role??'viewer')} error={error} busy={busy} drafts={drafts} onDraft={(id,text)=>setDrafts(current=>({...current,[id]:text}))} onReply={id=>void reply(id)} onRefresh={()=>void read()}/>{notice?<p role="status">{notice}</p>:null}{fetchedAt?<small>{locale==='en'?'Read at: ':'读取时间：'}{fetchedAt}</small>:null}{cursor?<button type="button" disabled={busy} onClick={()=>void read(cursor)}>{locale==='en'?'More comments':'更多评论'}</button>:null}</>:null}</div>;
}
